### ISSUE TITLE
support message groups

### ISSUE THREAD

**Issue by cglotr** [hooligram/hooligram-server#30]
### Diagrams
- [Consolidated](https://www.lucidchart.com/invitations/accept/06fb2086-c166-4d11-8146-6c1fba8eeeda) (_No tick support yet_)
- [Amir](https://www.lucidchart.com/invitations/accept/9eb299f5-bcf1-46bb-889f-ba41913a5c45)
- [Imran](https://www.lucidchart.com/invitations/accept/d3c15046-0532-476c-8ef3-b8764a826ad6)

#### Happy path scenarios
1. A user (sender) in a group of 5 sends a message to the group whereby all the 4 other members (recipients) are also online. Server will receive the message and will let the sender know of the message receipt. The server will send the message to each recipient. They will get the message and each recipient will let the sender know of the message receipt through the server.

2. A user (sender) in 1-to-1 chat sends a message to the other person (recipient), who is also online. The server will receive the message and will let the sender know of the message receipt. Server will send the message to the recipient. The recipient will get the message and will let the sender of the message receipt through the server.

#### Other scenarios (edge cases)
1. A user (sender) in a group of 5 sends a message to the group whereby one of the members are not online. For the online recipients, same business logic as happy path applies. For the offline recipient, server will have to remember to send the message to him when the he is back online. The recipient will let the sender know of the message receipt through the server.

2. Same as (1) except when recipient tries to let the sender know of the message receipt through the server, the sender has gone offline. When the sender goes back online, server will have to remember to send the message receipt to the sender.

3. Same as (1) except sender sends multiple messages and some of the messages have reached the recipients and some have not (for any reason). Server must let the sender know which message reached the recipients and which did not.

### Requirements
* Client can send many messages
* Client can receive many messages
* Message must have a sender
* Message must have a recipient
* Message must have an id
* Message must have a text
* Message must have a sent date
* Message must have a delivered date
* Sender must be notified that message has been sent to the server
* Sender must be notified that message has been delivered to the recipient
* Message id is generated by the server
* Message is deleted on the server once message is `sent` & `delivered` successfully (?)

### Implementation steps
- ~[ ] Use migration library - [pressly/goose](https://github.com/pressly/goose)* (or should this be a different issue?)~
- [x] Add `message_group` table
- [x] Add  `message_group_member` table
- [x] Add  `message` table
- [x] Add  `message_pending_delivery` table
- [x] Add  `message_pending_receipt` table
- [x] Support actions for sending messages
- [x] Support actions for delivering messages
- [x] Support actions for receiving messages (message receipt)

### Implementation happy path (some details omitted for readability)
[Sender] --- {MESSAGING_SEND_REQUEST} ---> [Server]
[Server] --- {MESSAGING_SEND_SUCCESS} ---> [Sender]
for each recipient
* [Server] --- {MESSAGING_DELIVER_REQUEST} ---> [Recipient]
* Server inserts a row into `message_pending_delivery` table
* [Recipient] --- {MESSAGING_DELIVER_SUCCESS} ---> [Server]
* Server deletes a row from `message_pending_delivery` table
* [Server] --- {MESSAGING_RECEIPT_REQUEST} ---> [Sender]
* Server inserts a row into `message_pending_receipt` table
* [Sender] --- {MESSAGING_RECEIPT_SUCCESS} ---> [Server]
* Server deletes a row from `message_pending_receipt` table

#### ~Migration~
~On server start up, apply each migration in list of migration files in order if not applied yet.~

#### message table
| Column Name | Type | Constraint |
| --- | :--- | :--- |
| id | INTEGER | PRIMARY KEY, NOT NULL, AUTO INCREMENT |
| message_group_id | INTEGER | FOREIGN KEY REFERENCES (message_group.id), NOT NULL |
| content | TEXT | NOT NULL |

#### message_pending_delivery table
Stores message pending for delivery from a sender to a single recipient. Insert a row into this table irrespective of whether **recipient is offline or online**. Delete the row when recipient receives the message delivery from the sender (`MESSAGING_DELIVERY_SUCCESS`).

| Column Name | Type | Constraint |
| --- | :--- | :--- |
| message_id | INTEGER | FOREIGN KEY REFERENCES (message.id), NOT NULL |
| sender_id | INTEGER | FOREIGN KEY REFERENCES (client.id), NOT NULL |
| recipient_id | INTEGER | FOREIGN KEY REFERENCES (client.id), NOT NULL |
| date_sent | TIMESTAMP | |

#### message_pending_receipt table
Stores message pending for receipt from a single recipient to the sender. Insert a row into this table irrespective of whether the **sender is offline or online**. Delete the row when sender receives the message receipt from the recipient (`MESSAGING_RECEIPT_SUCCESS`).

| Column Name | Type | Constraint |
| --- | :--- | :--- |
| message_id | INTEGER | FOREIGN KEY REFERENCES (message.id), NOT NULL |
| sender_id | INTEGER | FOREIGN KEY REFERENCES (client.id), NOT NULL |
| recipient_id | INTEGER | FOREIGN KEY REFERENCES (client.id), NOT NULL |
| date_delivered | TIMESTAMP | |

#### message_group table
| Column Name | Type | Constraint |
| --- | :--- | :--- |
| id | INTEGER | PRIMARY KEY, NOT NULL, AUTO INCREMENT |
| name | varchar(30) | NOT NULL |
| date_created | TIMESTAMP | NOT NULL |

#### message_group_member table
| Column Name | Type | Constraint |
| --- | :--- | :--- |
| message_group_id | INTEGER | FOREIGN KEY REFERENCES (message_group.id), NOT NULL |
| member_id | INTEGER | FOREIGN KEY REFERENCES (client.id), NOT NULL |

Constraints:
* UNIQUE (message_group_id, member_id)

#### Send message
*Sender sends a message to server*. This should trigger the server to find all group members. For each member of group add a row to `message_receipt` table.
```
{
  "type": "MESSAGING_SEND_REQUEST",
  "payload": {
    "message_identifier": <integer>, // generated and for use by sender locally only
    "message_text": <string>,
    "sender_id": <integer>, // user id
    "message_group_id": <integer>
  }
}
```
*Server responds to sender*. In addition to `message_identifier` and `date_sent` server provides `message_id` so sender can be notified of message delivery.
```
{
  "type": "MESSAGING_SEND_SUCCESS",
  "payload": {
    "message_identifier": <integer>, // generated and for use by sender locally only
    "message_id": <integer>,
    "date_sent": <integer> // epoch
  }
}
```

#### Deliver message
*Server delivers message to each recipient*. This should trigger an insert into a row in `message_pending_delivery`.
```
{
  "type": "MESSAGING_DELIVER_REQUEST",
  "payload": {
    "message_id": <integer>,
    "sender_id": <integer>,
    "message_text": <string>, // needed only by recipients
    "date_delivered": "<integer>" // epoch
  }
}
```
*Each recipients respond to server*. This should trigger the server to remove a row from `message_pending_delivery`
```
{
  "type": "MESSAGING_DELIVER_SUCCESS",
  "payload": {
    "message_id": <integer>,
    "date_delivered": "<integer>" // epoch
  }
}
```

#### Acknowledge message receipt
*Server lets sender know that a recipient has received the message*
```
{
  "type": "MESSAGING_RECEIPT_REQUEST",
  "payload": {
    "message_id": <integer>,
    "recipient_id": <integer>
  }
}
```
*Sender lets server know that the sender knows that recipient has received the message*
```
{
  "type": "MESSAGING_RECEIPT_SUCCESS",
  "payload": {
    "message_id": <integer>,
    "recipient_id": <integer>
  }
}
```

**Comment by imranariffin** [comment]
@cglotr updated the issue description with the design spec. Lmk if anything is incorrect, inaccurate or missing.

**Comment by cglotr** [comment]
@imranariffin I don't think we need to have a _Message_ table on the server

**Comment by cglotr** [comment]
@imranariffin 

I think we will need to freeze client development until we have a working message group API on the server. Working on the client right now does not make sense to me since it is bound to change depending on the API from the server.

I have found a great video pertaining to this [here](https://www.youtube.com/watch?v=vvhC64hQZMk).

I will try to come up with message group design too I guess and we can match and compare.

What the server should support:
- Direct message
- Group message
- Sent, Delivered, Read ticks
- List of contacts?
- New group?

**Comment by imranariffin** [comment]
Breakdown:
- [x] Support messaging without status (#34)
- [x] Support create group (#35)
- [x] Support add member into an existing group (#36)

@cglotr @imranariffin
